### ISSUE TITLE
other project: face_verification has no issues? how to ask a question?

### ISSUE THREAD

**Issue by ozett** [tempdata73/MtcnnMaskDetection#2]
hi,
i found your interesting projects and repos on github.

here your activated issues, so i use it to ask something for your repo "face_verification":

will you open issues there? would be great to ask about details how/which to download model and if tensorflow 2.x is compatible. i would give it a try to see the demo running on my system.

may push this over to newly issues on face_verification --> https://github.com/tempdata73/face_verification ?

greatly appreciate that, thx,
ozett

**Comment by tempdata73** [comment]
Hello,

Thanks for your interest in my projects. I just opened the issues section
on the face verification repository, so feel absolutely free to comment. As
mentioned in the README.md, I used the pretrained FaceNet model from
another repo, and to the best of my knowledge, it only runs on tensorflow
1.7 (not even 1.15!). To avoid compatibility issues with other projects, I
recommend you use a virtual environment and then run the requirements file.
